### ISSUE TITLE
Partners tab

### ISSUE THREAD

**Issue by ThomasGaubert** [FreetailHackers/freetailhackers.github.io#2]
Add a Partners/"Partner with Us" option to the navbar that either:
- Links directly to Partner section of main page
- Links to separate Partners page (possibly in addition to the pre-existing Partner section on the main page)

Either solution should include valid contact info, partnership PDF, etc. per Corporate team. To be implemented with final design.

**Comment by rohitdatta** [comment]
Working on fix with partners branch
