### ISSUE TITLE
Fix appearance on smaller screens

### ISSUE THREAD

**Issue by ThomasGaubert** [FreetailHackers/freetailhackers.github.io#6]
On smaller screens, some text is too big causing the site to extend horizontally beyond the edge of the screen. Titles also wrap to the next line which I suppose we should try to avoid. Adjusting text size should address both.

**Comment by rohitdatta** [comment]
Works for everything except very long words. Should that happen, see [global.scss](https://github.com/FreetailHackers/freetailhackers.github.io/blob/c33dc6e5e5af3465cb53382a620ceee9b1470c99/sass/global.scss#L165) for more details on how to implement.
